bot:
  id: "CLIENT_ID"
  token: "BOT_TOKEN"
  secret: "CLIENT_SECRET"
  host: "127.0.0.1"
  port: 80

guild:
  id: "GUILD_ID"

roles:
  0:
    id: "ROLE_ID"
    permission: "mcordsync.role.0"

mysql:
  host: "127.0.0.1"
  port: 3306
  database: "DatabaseName"
  table: "mcordsync"
  username: "root"
  password: "password"



