name: MCordSync
version: '${project.version}'
main: com.pnternn.mcordsync.MCordSync
author: cengiz1x, pnternn
api-version: '1.19'
commands:
  mcordsync:
    description: Link your Discord account to your Minecraft account
  report:
    description: report
  mcordsync-admin:
    description: Admin P0wer
    permission: op
